create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  person text not null check (person in ('Nam','Neel','Mei','Jayz')),
  workout_date date not null,
  exercise text not null,
  weight text not null default '',
  reps text not null default '',
  note text not null default '',
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(person, workout_date, exercise)
);
alter table public.workout_logs enable row level security;
drop policy if exists "crew can read workouts" on public.workout_logs;
drop policy if exists "crew can add workouts" on public.workout_logs;
drop policy if exists "crew can update workouts" on public.workout_logs;
create policy "crew can read workouts" on public.workout_logs for select to anon, authenticated using (true);
create policy "crew can add workouts" on public.workout_logs for insert to anon, authenticated with check (true);
create policy "crew can update workouts" on public.workout_logs for update to anon, authenticated using (true) with check (true);
