import {useEffect,useMemo,useState} from "react";
import {CalendarDays,Check,ChevronLeft,ChevronRight,Dumbbell,LoaderCircle,Save,Sparkles} from "lucide-react";
import {supabase} from "./supabase";

const PEOPLE=[{name:"Nam",color:"#f4a6b8",emoji:"🐻"},{name:"Neel",color:"#9bbfe0",emoji:"🐳"},{name:"Mei",color:"#a9d6bd",emoji:"🐰"},{name:"Jayz",color:"#c5b2e6",emoji:"🐣"}];
const PLANS={push:{label:"Push day",subtitle:"Chest · shoulders · triceps",sticker:"🌸",groups:[["Chest",["Incline dumbbell press","Pec fly machine","Push ups"]],["Shoulders",["Dumbbell shoulder press","Lateral raises","Unilateral reverse pec fly machine"]],["Triceps",["Triceps pull-down"]]]},pull:{label:"Pull day",subtitle:"Back · biceps",sticker:"🫐",groups:[["Back",["Lat pulldown","Seated rows","Assisted pull-ups"]],["Biceps",["Seated wrist curls","Dumbbell curls","Reverse wrist curls","Hammer curls"]]]},legs:{label:"Legs + abs",subtitle:"Lower body · core",sticker:"🍑",groups:[["Legs",["Leg curls","Leg extension","Calf raises","Leg press"]],["Abs",["Decline situps"]]]},rest:{label:"Rest day",subtitle:"Recover · stretch · reset",sticker:"☁️",groups:[]}} as const;
type PlanKey=keyof typeof PLANS; type Entry={weight:string;reps:string;note:string;completed:boolean};
const dayPlan:PlanKey[]=["rest","push","pull","legs","push","pull","legs"];
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const fromIso=(value:string)=>{const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d)};

export default function App(){
 const [person,setPerson]=useState("Nam"),[date,setDate]=useState(()=>iso(new Date())),[entries,setEntries]=useState<Record<string,Entry>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState<string|null>(null),[saved,setSaved]=useState<string|null>(null),[error,setError]=useState("");
 const selected=useMemo(()=>fromIso(date),[date]),plan=PLANS[dayPlan[selected.getDay()]],exercises=plan.groups.flatMap(([,items])=>[...items]),done=exercises.filter(x=>entries[x]?.completed).length;
 useEffect(()=>{let active=true;setLoading(true);setError("");supabase.from("workout_logs").select("exercise,weight,reps,note,completed").eq("person",person).eq("workout_date",date).then(({data,error})=>{if(!active)return;if(error){setError("Run supabase/schema.sql once to activate saving.");setEntries({})}else{const next:Record<string,Entry>={};for(const row of data||[])next[row.exercise]={weight:row.weight,reps:row.reps,note:row.note,completed:row.completed};setEntries(next)}setLoading(false)});return()=>{active=false}},[person,date]);
 const move=(n:number)=>{const d=fromIso(date);d.setDate(d.getDate()+n);setDate(iso(d))};
 const update=(exercise:string,field:keyof Entry,value:string|boolean)=>setEntries(prev=>{const current=prev[exercise]??{weight:"",reps:"",note:"",completed:false};return {...prev,[exercise]:{...current,[field]:value}}});
 const save=async(exercise:string)=>{setSaving(exercise);setError("");const entry=entries[exercise]||{weight:"",reps:"",note:"",completed:false};const {error}=await supabase.from("workout_logs").upsert({person,workout_date:date,exercise,...entry,updated_at:new Date().toISOString()},{onConflict:"person,workout_date,exercise"});setSaving(null);if(error)setError("Could not save yet. Please check the Supabase setup.");else{setSaved(exercise);window.setTimeout(()=>setSaved(null),1500)}};
 return <main><div className="ambient one"/><div className="ambient two"/><div className="shell"><header><div className="brand"><span className="mark"><Dumbbell size={20}/></span><div><h1>Four Friends</h1><p>little steps, stronger together</p></div></div><div className="sticker">⭐ <span>show up!</span></div></header>
 <section className="profiles" aria-label="Choose person">{PEOPLE.map(p=><button key={p.name} className={`profile ${person===p.name?"active":""}`} style={{"--person":p.color} as React.CSSProperties} onClick={()=>setPerson(p.name)}><span>{p.emoji}</span>{p.name}</button>)}</section>
 <section className="date"><button aria-label="Previous day" onClick={()=>move(-1)}><ChevronLeft/></button><div><CalendarDays size={16}/><span>{selected.toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long"})}</span><input aria-label="Choose date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button aria-label="Next day" onClick={()=>move(1)}><ChevronRight/></button></section>
 <section className="plan"><div><span className="eyebrow">TODAY’S PLAN</span><h2>{plan.label} <span>{plan.sticker}</span></h2><p>{plan.subtitle}</p></div>{exercises.length>0&&<div className="progress"><strong>{done}/{exercises.length}</strong><span> done</span><div><i style={{width:`${done/exercises.length*100}%`}}/></div></div>}</section>{error&&<div className="error">{error}</div>}
 {loading?<div className="state"><LoaderCircle className="spin"/>Loading {person}’s plan…</div>:plan.groups.length===0?<div className="rest"><div>☁️</div><h3>Rest is part of the plan.</h3><p>Take a walk, stretch a little, and come back fresh tomorrow.</p></div>:<div className="groups">{plan.groups.map(([group,items])=><section className="group" key={group}><div className="group-title"><span>{group}</span><i/></div><div className="list">{items.map(exercise=>{const e=entries[exercise]||{weight:"",reps:"",note:"",completed:false};return <article className={`exercise ${e.completed?"complete":""}`} key={exercise}><button className="check" aria-label={`Mark ${exercise} complete`} onClick={()=>update(exercise,"completed",!e.completed)}>{e.completed&&<Check size={17}/>}</button><div><h3>{exercise}</h3><div className="fields"><label><span>Weight</span><div><input inputMode="decimal" placeholder="—" value={e.weight} onChange={x=>update(exercise,"weight",x.target.value)}/><b>kg</b></div></label><label><span>Reps</span><div><input inputMode="numeric" placeholder="—" value={e.reps} onChange={x=>update(exercise,"reps",x.target.value)}/><b>reps</b></div></label><label className="note"><span>Note</span><input placeholder="How did it feel?" value={e.note} onChange={x=>update(exercise,"note",x.target.value)}/></label></div></div><button className={`save ${saved===exercise?"saved":""}`} onClick={()=>save(exercise)} disabled={saving===exercise}>{saving===exercise?<LoaderCircle className="spin"/>:saved===exercise?<Check/>:<Save/>}<span>{saved===exercise?"Saved":"Save"}</span></button></article>})}</div></section>)}</div>}
 <footer><Sparkles size={15}/> made for Nam, Neel, Mei & Jayz</footer></div></main>
}
